sources:

  - source_id: census_imports
    authority: us_government
    category: trade_flows
    type: api
    endpoint: https://api.census.gov/data/timeseries/intltrade/imports
    auth:
      required: true
      env_key: CENSUS_API_KEY
    cadence: monthly
    raw_format: json
    canonical_schema:
      - hs_code
      - country_code
      - value_usd
      - period

  - source_id: census_exports
    authority: us_government
    category: trade_flows
    type: api
    endpoint: https://api.census.gov/data/timeseries/intltrade/exports
    auth:
      required: true
      env_key: CENSUS_API_KEY
    cadence: monthly
    raw_format: json

  - source_id: usitc_hts
    authority: us_government
    category: tariff_structure
    type: pdf
    endpoint: https://hts.usitc.gov/current
    cadence: yearly
    raw_format: pdf

  - source_id: cbp_rulings
    authority: us_government
    category: regulatory_interpretation
    type: api
    endpoint: https://rulings.cbp.gov/api/rulings
    cadence: weekly
    raw_format: json

  - source_id: un_comtrade
    authority: united_nations
    category: global_trade
    type: api
    endpoint: https://comtrade.un.org/api/get
    auth:
      required: true
      env_key: UN_COMTRADE_KEY
    cadence: yearly
    raw_format: json

  - source_id: ustr_ftas
    authority: us_government
    category: trade_policy
    type: xls
    endpoint: https://ustr.gov/sites/default/files/fta_data.xlsx
    cadence: quarterly
    raw_format: xls
